import { ethers } from "ethers";

// Replace this with your deployed contract address after running deploy.js
const contractAddress = "0xYourDeployedContractAddress";

// Replace this with ABI generated by Hardhat
import PaithaniABI from "./PaithaniSupplyChain.json";

// Connect to local blockchain
const provider = new ethers.providers.Web3Provider(window.ethereum);
const signer = provider.getSigner();
export const contract = new ethers.Contract(contractAddress, PaithaniABI.abi, signer);